queue_rules:
  - name: default
    conditions:
      # Conditions to get out of the queue (= merged)
      - check-success~=build \(2.13.\d+\)
      - check-success~=build \(3.1.\d+\)

pull_request_rules:
  - name: Label Scala Steward PRs
    conditions:
      - author=scala-steward
    actions:
      label:
        add: [dependencies, scala]

  - name: Merge dependency-update PRs
    conditions:
      - base=main
      - label=dependencies
      - check-success~=build \(2.13.\d+\)
      - check-success~=build \(3.1.\d+\)
    actions:
      queue:
        name: default
        method: squash
